version: "3.8"

services:
  app:
    build: .
    image: task-tracker
    container_name: task-tracker
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres
    command: ["npm", "run", "start"]

  postgres:
    image: postgres:16 # <-- VALID VERSION
    container_name: task-tracker-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

    # depends_on:
    #   - redis
    # environment:
    #   REDIS_HOST: ${REDIS_HOST}
    #   REDIS_PORT: ${REDIS_PORT}
    #   REDIS_PWD: ${REDIS_PWD}

  # redis:
  #   image: redis:latest
  #   container_name: redis_c
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   command: ["redis-server", "--appendonly", "yes"]
# volumes:
#   redis-data:
